# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agenda.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agenda.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61genda.proto\"9\n\x06Pessoa\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x65lular\x18\x02 \x01(\t\x12\x10\n\x08telefone\x18\x03 \x01(\t\"\x1a\n\nNomePessoa\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x1d\n\x0c\x42ooleanReply\x12\r\n\x05reply\x18\x01 \x01(\x08\"&\n\x0f\x43ontactsRequest\x12\x13\n\x0bListaAgenda\x18\x01 \x01(\x08\x32\xb2\x01\n\x07Manager\x12%\n\tAddPessoa\x12\x07.Pessoa\x1a\r.BooleanReply\"\x00\x12)\n\tDelPessoa\x12\x0b.NomePessoa\x1a\r.BooleanReply\"\x00\x12\'\n\x0b\x42uscaPessoa\x12\x0b.NomePessoa\x1a\x07.Pessoa\"\x00\x30\x01\x12,\n\x0bListaAgenda\x12\x10.ContactsRequest\x1a\x07.Pessoa\"\x00\x30\x01\x62\x06proto3')
)




_PESSOA = _descriptor.Descriptor(
  name='Pessoa',
  full_name='Pessoa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Pessoa.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='celular', full_name='Pessoa.celular', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telefone', full_name='Pessoa.telefone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=73,
)


_NOMEPESSOA = _descriptor.Descriptor(
  name='NomePessoa',
  full_name='NomePessoa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='NomePessoa.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=101,
)


_BOOLEANREPLY = _descriptor.Descriptor(
  name='BooleanReply',
  full_name='BooleanReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='BooleanReply.reply', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=132,
)


_CONTACTSREQUEST = _descriptor.Descriptor(
  name='ContactsRequest',
  full_name='ContactsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ListaAgenda', full_name='ContactsRequest.ListaAgenda', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['Pessoa'] = _PESSOA
DESCRIPTOR.message_types_by_name['NomePessoa'] = _NOMEPESSOA
DESCRIPTOR.message_types_by_name['BooleanReply'] = _BOOLEANREPLY
DESCRIPTOR.message_types_by_name['ContactsRequest'] = _CONTACTSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pessoa = _reflection.GeneratedProtocolMessageType('Pessoa', (_message.Message,), dict(
  DESCRIPTOR = _PESSOA,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:Pessoa)
  ))
_sym_db.RegisterMessage(Pessoa)

NomePessoa = _reflection.GeneratedProtocolMessageType('NomePessoa', (_message.Message,), dict(
  DESCRIPTOR = _NOMEPESSOA,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:NomePessoa)
  ))
_sym_db.RegisterMessage(NomePessoa)

BooleanReply = _reflection.GeneratedProtocolMessageType('BooleanReply', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEANREPLY,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:BooleanReply)
  ))
_sym_db.RegisterMessage(BooleanReply)

ContactsRequest = _reflection.GeneratedProtocolMessageType('ContactsRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTSREQUEST,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:ContactsRequest)
  ))
_sym_db.RegisterMessage(ContactsRequest)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ManagerStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.AddPessoa = channel.unary_unary(
          '/Manager/AddPessoa',
          request_serializer=Pessoa.SerializeToString,
          response_deserializer=BooleanReply.FromString,
          )
      self.DelPessoa = channel.unary_unary(
          '/Manager/DelPessoa',
          request_serializer=NomePessoa.SerializeToString,
          response_deserializer=BooleanReply.FromString,
          )
      self.BuscaPessoa = channel.unary_stream(
          '/Manager/BuscaPessoa',
          request_serializer=NomePessoa.SerializeToString,
          response_deserializer=Pessoa.FromString,
          )
      self.ListaAgenda = channel.unary_stream(
          '/Manager/ListaAgenda',
          request_serializer=ContactsRequest.SerializeToString,
          response_deserializer=Pessoa.FromString,
          )


  class ManagerServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def AddPessoa(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def DelPessoa(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def BuscaPessoa(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ListaAgenda(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'AddPessoa': grpc.unary_unary_rpc_method_handler(
            servicer.AddPessoa,
            request_deserializer=Pessoa.FromString,
            response_serializer=BooleanReply.SerializeToString,
        ),
        'DelPessoa': grpc.unary_unary_rpc_method_handler(
            servicer.DelPessoa,
            request_deserializer=NomePessoa.FromString,
            response_serializer=BooleanReply.SerializeToString,
        ),
        'BuscaPessoa': grpc.unary_stream_rpc_method_handler(
            servicer.BuscaPessoa,
            request_deserializer=NomePessoa.FromString,
            response_serializer=Pessoa.SerializeToString,
        ),
        'ListaAgenda': grpc.unary_stream_rpc_method_handler(
            servicer.ListaAgenda,
            request_deserializer=ContactsRequest.FromString,
            response_serializer=Pessoa.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaManagerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def AddPessoa(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def DelPessoa(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def BuscaPessoa(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ListaAgenda(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaManagerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def AddPessoa(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    AddPessoa.future = None
    def DelPessoa(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    DelPessoa.future = None
    def BuscaPessoa(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    def ListaAgenda(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_Manager_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Manager', 'AddPessoa'): Pessoa.FromString,
      ('Manager', 'BuscaPessoa'): NomePessoa.FromString,
      ('Manager', 'DelPessoa'): NomePessoa.FromString,
      ('Manager', 'ListaAgenda'): ContactsRequest.FromString,
    }
    response_serializers = {
      ('Manager', 'AddPessoa'): BooleanReply.SerializeToString,
      ('Manager', 'BuscaPessoa'): Pessoa.SerializeToString,
      ('Manager', 'DelPessoa'): BooleanReply.SerializeToString,
      ('Manager', 'ListaAgenda'): Pessoa.SerializeToString,
    }
    method_implementations = {
      ('Manager', 'AddPessoa'): face_utilities.unary_unary_inline(servicer.AddPessoa),
      ('Manager', 'BuscaPessoa'): face_utilities.unary_stream_inline(servicer.BuscaPessoa),
      ('Manager', 'DelPessoa'): face_utilities.unary_unary_inline(servicer.DelPessoa),
      ('Manager', 'ListaAgenda'): face_utilities.unary_stream_inline(servicer.ListaAgenda),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Manager_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Manager', 'AddPessoa'): Pessoa.SerializeToString,
      ('Manager', 'BuscaPessoa'): NomePessoa.SerializeToString,
      ('Manager', 'DelPessoa'): NomePessoa.SerializeToString,
      ('Manager', 'ListaAgenda'): ContactsRequest.SerializeToString,
    }
    response_deserializers = {
      ('Manager', 'AddPessoa'): BooleanReply.FromString,
      ('Manager', 'BuscaPessoa'): Pessoa.FromString,
      ('Manager', 'DelPessoa'): BooleanReply.FromString,
      ('Manager', 'ListaAgenda'): Pessoa.FromString,
    }
    cardinalities = {
      'AddPessoa': cardinality.Cardinality.UNARY_UNARY,
      'BuscaPessoa': cardinality.Cardinality.UNARY_STREAM,
      'DelPessoa': cardinality.Cardinality.UNARY_UNARY,
      'ListaAgenda': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Manager', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
